using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;
namespace Assets.Scripts.Game.Terrain
{
    public class MarchingCubes
    {
        private static readonly Vector3[] Vertices =
        {
            new Vector3(-0.5f, -0.5f, 0), new Vector3(0, -0.5f, 0.5f), new Vector3(0.5f, -0.5f, 0), new Vector3(0, -0.5f, -0.5f),
            new Vector3(-0.5f, 0.5f, 0), new Vector3(0, 0.5f, 0.5f), new Vector3(0.5f, 0.5f, 0), new Vector3(0, 0.5f, -0.5f),
            new Vector3(-0.5f, 0, -0.5f), new Vector3(-0.5f, 0, 0.5f), new Vector3(0.5f, 0, 0.5f), new Vector3(0.5f, 0, -0.5f),
        };
        private static readonly Vector3[] Normals =
        {
            new Vector3(-0.6f, -0.6f, -0.6f),new Vector3(-0.6f, -0.6f, 0.6f),new Vector3(-0.7f, -0.7f, -0.0f),new Vector3(0.6f, -0.6f, 0.6f),
            new Vector3(-0.0f, -0.7f, 0.7f),new Vector3(-0.0f, -1.0f, -0.0f),new Vector3(0.6f, -0.6f, -0.6f),new Vector3(-0.0f, -0.7f, -0.7f),
            new Vector3(0.7f, -0.7f, -0.0f),new Vector3(-0.6f, 0.6f, -0.6f),new Vector3(-0.7f, -0.0f, -0.7f),new Vector3(-1.0f, -0.0f, -0.0f),
            new Vector3(-0.7f, -0.0f, 0.7f),new Vector3(-0.0f, -0.0f, -1.0f),new Vector3(0.7f, -0.0f, -0.7f),new Vector3(-0.6f, 0.6f, 0.6f),
            new Vector3(-0.0f, -0.0f, 1.0f),new Vector3(-0.7f, 0.7f, -0.0f),new Vector3(-0.0f, 0.7f, 0.7f),new Vector3(-0.0f, 0.7f, -0.7f),
            new Vector3(-0.9f, 0.4f, -0.0f),new Vector3(-0.3f, -0.3f, -0.9f),new Vector3(0.4f, -0.9f, -0.0f),new Vector3(-0.3f, -0.3f, 0.9f),
            new Vector3(0.6f, 0.6f, 0.6f),new Vector3(0.7f, -0.0f, 0.7f),new Vector3(1.0f, -0.0f, -0.0f),new Vector3(-0.9f, -0.0f, -0.4f),
            new Vector3(-0.3f, -0.9f, 0.3f),new Vector3(0.4f, -0.0f, 0.9f),new Vector3(0.9f, -0.0f, 0.4f),new Vector3(0.3f, -0.9f, -0.3f),
            new Vector3(-0.4f, -0.0f, -0.9f),new Vector3(-0.0f, 0.4f, 0.9f),new Vector3(-0.9f, -0.3f, 0.3f),new Vector3(-0.0f, -0.9f, -0.4f),
            new Vector3(0.7f, 0.7f, -0.0f),new Vector3(0.9f, -0.3f, 0.3f),new Vector3(-0.0f, 1.0f, -0.0f),new Vector3(-0.3f, 0.9f, 0.3f),
            new Vector3(-0.0f, -0.4f, -0.9f),new Vector3(-0.9f, 0.3f, -0.3f),new Vector3(-0.0f, 0.9f, 0.4f),new Vector3(-0.4f, 0.9f, -0.0f),
            new Vector3(0.3f, 0.3f, 0.9f),new Vector3(0.9f, -0.4f, -0.0f),new Vector3(0.6f, 0.6f, -0.6f),new Vector3(-0.0f, -0.9f, 0.4f),
            new Vector3(-0.9f, -0.3f, -0.3f),new Vector3(-0.0f, 0.4f, -0.9f),new Vector3(0.9f, -0.3f, -0.3f),new Vector3(0.4f, -0.0f, -0.9f),
            new Vector3(-0.3f, -0.9f, -0.3f),new Vector3(-0.9f, -0.0f, 0.4f),new Vector3(-0.4f, -0.0f, 0.9f),new Vector3(0.3f, -0.9f, 0.3f),
            new Vector3(0.9f, -0.0f, -0.4f),new Vector3(-0.0f, 0.9f, -0.4f),new Vector3(-0.9f, 0.3f, 0.3f),new Vector3(-0.0f, -0.4f, 0.9f),
            new Vector3(-0.3f, 0.9f, -0.3f),new Vector3(0.3f, 0.3f, -0.9f),new Vector3(0.9f, 0.4f, -0.0f),new Vector3(0.3f, -0.3f, 0.9f),
            new Vector3(-0.4f, -0.9f, -0.0f),new Vector3(0.3f, -0.3f, -0.9f),new Vector3(0.4f, 0.9f, -0.0f),new Vector3(-0.3f, 0.3f, -0.9f),
            new Vector3(-0.9f, -0.4f, -0.0f),new Vector3(0.3f, 0.9f, -0.3f),new Vector3(0.9f, 0.3f, 0.3f),new Vector3(-0.3f, 0.3f, 0.9f),
            new Vector3(0.9f, 0.3f, -0.3f),new Vector3(0.3f, 0.9f, 0.3f)
        };

        private static readonly Dictionary<int, int[]> TriangleTable = new Dictionary<int, int[]>()
        {
            {0, new int[]{ }},
            {3, new int[]{0, 1, 2}},
            {6, new int[]{0, 1, 2, 3, 4, 5}},
            {9, new int[]{0, 1, 2, 3, 4, 5, 6, 7, 8}},
            {12, new int[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}},
            {15, new int[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}},
        };

        private static readonly Vector3[][] VerticeTable = new Vector3[][]
        {
            new Vector3[] {},
            new Vector3[] {Vertices[0], Vertices[8], Vertices[3]},
            new Vector3[] {Vertices[0], Vertices[1], Vertices[9]},
            new Vector3[] {Vertices[1], Vertices[8], Vertices[3], Vertices[9], Vertices[8], Vertices[1]},
            new Vector3[] {Vertices[1], Vertices[2], Vertices[10]},
            new Vector3[] {Vertices[0], Vertices[8], Vertices[3], Vertices[1], Vertices[2], Vertices[10]},
            new Vector3[] {Vertices[9], Vertices[2], Vertices[10], Vertices[0], Vertices[2], Vertices[9]},
            new Vector3[] {Vertices[2], Vertices[8], Vertices[3], Vertices[2], Vertices[10], Vertices[8], Vertices[10], Vertices[9], Vertices[8]},
            new Vector3[] {Vertices[3], Vertices[11], Vertices[2]},
            new Vector3[] {Vertices[0], Vertices[11], Vertices[2], Vertices[8], Vertices[11], Vertices[0]},
            new Vector3[] {Vertices[1], Vertices[9], Vertices[0], Vertices[2], Vertices[3], Vertices[11]},
            new Vector3[] {Vertices[1], Vertices[11], Vertices[2], Vertices[1], Vertices[9], Vertices[11], Vertices[9], Vertices[8], Vertices[11]},
            new Vector3[] {Vertices[3], Vertices[10], Vertices[1], Vertices[11], Vertices[10], Vertices[3]},
            new Vector3[] {Vertices[0], Vertices[10], Vertices[1], Vertices[0], Vertices[8], Vertices[10], Vertices[8], Vertices[11], Vertices[10]},
            new Vector3[] {Vertices[3], Vertices[9], Vertices[0], Vertices[3], Vertices[11], Vertices[9], Vertices[11], Vertices[10], Vertices[9]},
            new Vector3[] {Vertices[9], Vertices[8], Vertices[10], Vertices[10], Vertices[8], Vertices[11]},
            new Vector3[] {Vertices[4], Vertices[7], Vertices[8]},
            new Vector3[] {Vertices[4], Vertices[3], Vertices[0], Vertices[7], Vertices[3], Vertices[4]},
            new Vector3[] {Vertices[0], Vertices[1], Vertices[9], Vertices[8], Vertices[4], Vertices[7]},
            new Vector3[] {Vertices[4], Vertices[1], Vertices[9], Vertices[4], Vertices[7], Vertices[1], Vertices[7], Vertices[3], Vertices[1]},
            new Vector3[] {Vertices[1], Vertices[2], Vertices[10], Vertices[8], Vertices[4], Vertices[7]},
            new Vector3[] {Vertices[3], Vertices[4], Vertices[7], Vertices[3], Vertices[0], Vertices[4], Vertices[1], Vertices[2], Vertices[10]},
            new Vector3[] {Vertices[9], Vertices[2], Vertices[10], Vertices[9], Vertices[0], Vertices[2], Vertices[8], Vertices[4], Vertices[7]},
            new Vector3[] {Vertices[2], Vertices[10], Vertices[9], Vertices[2], Vertices[9], Vertices[7], Vertices[2], Vertices[7], Vertices[3], Vertices[7], Vertices[9], Vertices[4]},
            new Vector3[] {Vertices[8], Vertices[4], Vertices[7], Vertices[3], Vertices[11], Vertices[2]},
            new Vector3[] {Vertices[11], Vertices[4], Vertices[7], Vertices[11], Vertices[2], Vertices[4], Vertices[2], Vertices[0], Vertices[4]},
            new Vector3[] {Vertices[9], Vertices[0], Vertices[1], Vertices[8], Vertices[4], Vertices[7], Vertices[2], Vertices[3], Vertices[11]},
            new Vector3[] {Vertices[4], Vertices[7], Vertices[11], Vertices[9], Vertices[4], Vertices[11], Vertices[9], Vertices[11], Vertices[2], Vertices[9], Vertices[2], Vertices[1]},
            new Vector3[] {Vertices[3], Vertices[10], Vertices[1], Vertices[3], Vertices[11], Vertices[10], Vertices[7], Vertices[8], Vertices[4]},
            new Vector3[] {Vertices[1], Vertices[11], Vertices[10], Vertices[1], Vertices[4], Vertices[11], Vertices[1], Vertices[0], Vertices[4], Vertices[7], Vertices[11], Vertices[4]},
            new Vector3[] {Vertices[4], Vertices[7], Vertices[8], Vertices[9], Vertices[0], Vertices[11], Vertices[9], Vertices[11], Vertices[10], Vertices[11], Vertices[0], Vertices[3]},
            new Vector3[] {Vertices[4], Vertices[7], Vertices[11], Vertices[4], Vertices[11], Vertices[9], Vertices[9], Vertices[11], Vertices[10]},
            new Vector3[] {Vertices[9], Vertices[5], Vertices[4]},
            new Vector3[] {Vertices[9], Vertices[5], Vertices[4], Vertices[0], Vertices[8], Vertices[3]},
            new Vector3[] {Vertices[0], Vertices[5], Vertices[4], Vertices[1], Vertices[5], Vertices[0]},
            new Vector3[] {Vertices[8], Vertices[5], Vertices[4], Vertices[8], Vertices[3], Vertices[5], Vertices[3], Vertices[1], Vertices[5]},
            new Vector3[] {Vertices[1], Vertices[2], Vertices[10], Vertices[9], Vertices[5], Vertices[4]},
            new Vector3[] {Vertices[3], Vertices[0], Vertices[8], Vertices[1], Vertices[2], Vertices[10], Vertices[4], Vertices[9], Vertices[5]},
            new Vector3[] {Vertices[5], Vertices[2], Vertices[10], Vertices[5], Vertices[4], Vertices[2], Vertices[4], Vertices[0], Vertices[2]},
            new Vector3[] {Vertices[2], Vertices[10], Vertices[5], Vertices[3], Vertices[2], Vertices[5], Vertices[3], Vertices[5], Vertices[4], Vertices[3], Vertices[4], Vertices[8]},
            new Vector3[] {Vertices[9], Vertices[5], Vertices[4], Vertices[2], Vertices[3], Vertices[11]},
            new Vector3[] {Vertices[0], Vertices[11], Vertices[2], Vertices[0], Vertices[8], Vertices[11], Vertices[4], Vertices[9], Vertices[5]},
            new Vector3[] {Vertices[0], Vertices[5], Vertices[4], Vertices[0], Vertices[1], Vertices[5], Vertices[2], Vertices[3], Vertices[11]},
            new Vector3[] {Vertices[2], Vertices[1], Vertices[5], Vertices[2], Vertices[5], Vertices[8], Vertices[2], Vertices[8], Vertices[11], Vertices[4], Vertices[8], Vertices[5]},
            new Vector3[] {Vertices[10], Vertices[3], Vertices[11], Vertices[10], Vertices[1], Vertices[3], Vertices[9], Vertices[5], Vertices[4]},
            new Vector3[] {Vertices[4], Vertices[9], Vertices[5], Vertices[0], Vertices[8], Vertices[1], Vertices[8], Vertices[10], Vertices[1], Vertices[8], Vertices[11], Vertices[10]},
            new Vector3[] {Vertices[5], Vertices[4], Vertices[0], Vertices[5], Vertices[0], Vertices[11], Vertices[5], Vertices[11], Vertices[10], Vertices[11], Vertices[0], Vertices[3]},
            new Vector3[] {Vertices[5], Vertices[4], Vertices[8], Vertices[5], Vertices[8], Vertices[10], Vertices[10], Vertices[8], Vertices[11]},
            new Vector3[] {Vertices[9], Vertices[7], Vertices[8], Vertices[5], Vertices[7], Vertices[9]},
            new Vector3[] {Vertices[9], Vertices[3], Vertices[0], Vertices[9], Vertices[5], Vertices[3], Vertices[5], Vertices[7], Vertices[3]},
            new Vector3[] {Vertices[0], Vertices[7], Vertices[8], Vertices[0], Vertices[1], Vertices[7], Vertices[1], Vertices[5], Vertices[7]},
            new Vector3[] {Vertices[1], Vertices[5], Vertices[3], Vertices[3], Vertices[5], Vertices[7]},
            new Vector3[] {Vertices[9], Vertices[7], Vertices[8], Vertices[9], Vertices[5], Vertices[7], Vertices[10], Vertices[1], Vertices[2]},
            new Vector3[] {Vertices[10], Vertices[1], Vertices[2], Vertices[9], Vertices[5], Vertices[0], Vertices[5], Vertices[3], Vertices[0], Vertices[5], Vertices[7], Vertices[3]},
            new Vector3[] {Vertices[8], Vertices[0], Vertices[2], Vertices[8], Vertices[2], Vertices[5], Vertices[8], Vertices[5], Vertices[7], Vertices[10], Vertices[5], Vertices[2]},
            new Vector3[] {Vertices[2], Vertices[10], Vertices[5], Vertices[2], Vertices[5], Vertices[3], Vertices[3], Vertices[5], Vertices[7]},
            new Vector3[] {Vertices[7], Vertices[9], Vertices[5], Vertices[7], Vertices[8], Vertices[9], Vertices[3], Vertices[11], Vertices[2]},
            new Vector3[] {Vertices[9], Vertices[5], Vertices[7], Vertices[9], Vertices[7], Vertices[2], Vertices[9], Vertices[2], Vertices[0], Vertices[2], Vertices[7], Vertices[11]},
            new Vector3[] {Vertices[2], Vertices[3], Vertices[11], Vertices[0], Vertices[1], Vertices[8], Vertices[1], Vertices[7], Vertices[8], Vertices[1], Vertices[5], Vertices[7]},
            new Vector3[] {Vertices[11], Vertices[2], Vertices[1], Vertices[11], Vertices[1], Vertices[7], Vertices[7], Vertices[1], Vertices[5]},
            new Vector3[] {Vertices[9], Vertices[5], Vertices[8], Vertices[8], Vertices[5], Vertices[7], Vertices[10], Vertices[1], Vertices[3], Vertices[10], Vertices[3], Vertices[11]},
            new Vector3[] {Vertices[5], Vertices[7], Vertices[0], Vertices[5], Vertices[0], Vertices[9], Vertices[7], Vertices[11], Vertices[0], Vertices[1], Vertices[0], Vertices[10], Vertices[11], Vertices[10], Vertices[0]},
            new Vector3[] {Vertices[11], Vertices[10], Vertices[0], Vertices[11], Vertices[0], Vertices[3], Vertices[10], Vertices[5], Vertices[0], Vertices[8], Vertices[0], Vertices[7], Vertices[5], Vertices[7], Vertices[0]},
            new Vector3[] {Vertices[11], Vertices[10], Vertices[5], Vertices[7], Vertices[11], Vertices[5]},
            new Vector3[] {Vertices[10], Vertices[6], Vertices[5]},
            new Vector3[] {Vertices[0], Vertices[8], Vertices[3], Vertices[5], Vertices[10], Vertices[6]},
            new Vector3[] {Vertices[9], Vertices[0], Vertices[1], Vertices[5], Vertices[10], Vertices[6]},
            new Vector3[] {Vertices[1], Vertices[8], Vertices[3], Vertices[1], Vertices[9], Vertices[8], Vertices[5], Vertices[10], Vertices[6]},
            new Vector3[] {Vertices[1], Vertices[6], Vertices[5], Vertices[2], Vertices[6], Vertices[1]},
            new Vector3[] {Vertices[1], Vertices[6], Vertices[5], Vertices[1], Vertices[2], Vertices[6], Vertices[3], Vertices[0], Vertices[8]},
            new Vector3[] {Vertices[9], Vertices[6], Vertices[5], Vertices[9], Vertices[0], Vertices[6], Vertices[0], Vertices[2], Vertices[6]},
            new Vector3[] {Vertices[5], Vertices[9], Vertices[8], Vertices[5], Vertices[8], Vertices[2], Vertices[5], Vertices[2], Vertices[6], Vertices[3], Vertices[2], Vertices[8]},
            new Vector3[] {Vertices[2], Vertices[3], Vertices[11], Vertices[10], Vertices[6], Vertices[5]},
            new Vector3[] {Vertices[11], Vertices[0], Vertices[8], Vertices[11], Vertices[2], Vertices[0], Vertices[10], Vertices[6], Vertices[5]},
            new Vector3[] {Vertices[0], Vertices[1], Vertices[9], Vertices[2], Vertices[3], Vertices[11], Vertices[5], Vertices[10], Vertices[6]},
            new Vector3[] {Vertices[5], Vertices[10], Vertices[6], Vertices[1], Vertices[9], Vertices[2], Vertices[9], Vertices[11], Vertices[2], Vertices[9], Vertices[8], Vertices[11]},
            new Vector3[] {Vertices[6], Vertices[3], Vertices[11], Vertices[6], Vertices[5], Vertices[3], Vertices[5], Vertices[1], Vertices[3]},
            new Vector3[] {Vertices[0], Vertices[8], Vertices[11], Vertices[0], Vertices[11], Vertices[5], Vertices[0], Vertices[5], Vertices[1], Vertices[5], Vertices[11], Vertices[6]},
            new Vector3[] {Vertices[3], Vertices[11], Vertices[6], Vertices[0], Vertices[3], Vertices[6], Vertices[0], Vertices[6], Vertices[5], Vertices[0], Vertices[5], Vertices[9]},
            new Vector3[] {Vertices[6], Vertices[5], Vertices[9], Vertices[6], Vertices[9], Vertices[11], Vertices[11], Vertices[9], Vertices[8]},
            new Vector3[] {Vertices[5], Vertices[10], Vertices[6], Vertices[4], Vertices[7], Vertices[8]},
            new Vector3[] {Vertices[4], Vertices[3], Vertices[0], Vertices[4], Vertices[7], Vertices[3], Vertices[6], Vertices[5], Vertices[10]},
            new Vector3[] {Vertices[1], Vertices[9], Vertices[0], Vertices[5], Vertices[10], Vertices[6], Vertices[8], Vertices[4], Vertices[7]},
            new Vector3[] {Vertices[10], Vertices[6], Vertices[5], Vertices[1], Vertices[9], Vertices[7], Vertices[1], Vertices[7], Vertices[3], Vertices[7], Vertices[9], Vertices[4]},
            new Vector3[] {Vertices[6], Vertices[1], Vertices[2], Vertices[6], Vertices[5], Vertices[1], Vertices[4], Vertices[7], Vertices[8]},
            new Vector3[] {Vertices[1], Vertices[2], Vertices[5], Vertices[5], Vertices[2], Vertices[6], Vertices[3], Vertices[0], Vertices[4], Vertices[3], Vertices[4], Vertices[7]},
            new Vector3[] {Vertices[8], Vertices[4], Vertices[7], Vertices[9], Vertices[0], Vertices[5], Vertices[0], Vertices[6], Vertices[5], Vertices[0], Vertices[2], Vertices[6]},
            new Vector3[] {Vertices[7], Vertices[3], Vertices[9], Vertices[7], Vertices[9], Vertices[4], Vertices[3], Vertices[2], Vertices[9], Vertices[5], Vertices[9], Vertices[6], Vertices[2], Vertices[6], Vertices[9]},
            new Vector3[] {Vertices[3], Vertices[11], Vertices[2], Vertices[7], Vertices[8], Vertices[4], Vertices[10], Vertices[6], Vertices[5]},
            new Vector3[] {Vertices[5], Vertices[10], Vertices[6], Vertices[4], Vertices[7], Vertices[2], Vertices[4], Vertices[2], Vertices[0], Vertices[2], Vertices[7], Vertices[11]},
            new Vector3[] {Vertices[0], Vertices[1], Vertices[9], Vertices[4], Vertices[7], Vertices[8], Vertices[2], Vertices[3], Vertices[11], Vertices[5], Vertices[10], Vertices[6]},
            new Vector3[] {Vertices[9], Vertices[2], Vertices[1], Vertices[9], Vertices[11], Vertices[2], Vertices[9], Vertices[4], Vertices[11], Vertices[7], Vertices[11], Vertices[4], Vertices[5], Vertices[10], Vertices[6]},
            new Vector3[] {Vertices[8], Vertices[4], Vertices[7], Vertices[3], Vertices[11], Vertices[5], Vertices[3], Vertices[5], Vertices[1], Vertices[5], Vertices[11], Vertices[6]},
            new Vector3[] {Vertices[5], Vertices[1], Vertices[11], Vertices[5], Vertices[11], Vertices[6], Vertices[1], Vertices[0], Vertices[11], Vertices[7], Vertices[11], Vertices[4], Vertices[0], Vertices[4], Vertices[11]},
            new Vector3[] {Vertices[0], Vertices[5], Vertices[9], Vertices[0], Vertices[6], Vertices[5], Vertices[0], Vertices[3], Vertices[6], Vertices[11], Vertices[6], Vertices[3], Vertices[8], Vertices[4], Vertices[7]},
            new Vector3[] {Vertices[6], Vertices[5], Vertices[9], Vertices[6], Vertices[9], Vertices[11], Vertices[4], Vertices[7], Vertices[9], Vertices[7], Vertices[11], Vertices[9]},
            new Vector3[] {Vertices[10], Vertices[4], Vertices[9], Vertices[6], Vertices[4], Vertices[10]},
            new Vector3[] {Vertices[4], Vertices[10], Vertices[6], Vertices[4], Vertices[9], Vertices[10], Vertices[0], Vertices[8], Vertices[3]},
            new Vector3[] {Vertices[10], Vertices[0], Vertices[1], Vertices[10], Vertices[6], Vertices[0], Vertices[6], Vertices[4], Vertices[0]},
            new Vector3[] {Vertices[8], Vertices[3], Vertices[1], Vertices[8], Vertices[1], Vertices[6], Vertices[8], Vertices[6], Vertices[4], Vertices[6], Vertices[1], Vertices[10]},
            new Vector3[] {Vertices[1], Vertices[4], Vertices[9], Vertices[1], Vertices[2], Vertices[4], Vertices[2], Vertices[6], Vertices[4]},
            new Vector3[] {Vertices[3], Vertices[0], Vertices[8], Vertices[1], Vertices[2], Vertices[9], Vertices[2], Vertices[4], Vertices[9], Vertices[2], Vertices[6], Vertices[4]},
            new Vector3[] {Vertices[0], Vertices[2], Vertices[4], Vertices[4], Vertices[2], Vertices[6]},
            new Vector3[] {Vertices[8], Vertices[3], Vertices[2], Vertices[8], Vertices[2], Vertices[4], Vertices[4], Vertices[2], Vertices[6]},
            new Vector3[] {Vertices[10], Vertices[4], Vertices[9], Vertices[10], Vertices[6], Vertices[4], Vertices[11], Vertices[2], Vertices[3]},
            new Vector3[] {Vertices[0], Vertices[8], Vertices[2], Vertices[2], Vertices[8], Vertices[11], Vertices[4], Vertices[9], Vertices[10], Vertices[4], Vertices[10], Vertices[6]},
            new Vector3[] {Vertices[3], Vertices[11], Vertices[2], Vertices[0], Vertices[1], Vertices[6], Vertices[0], Vertices[6], Vertices[4], Vertices[6], Vertices[1], Vertices[10]},
            new Vector3[] {Vertices[6], Vertices[4], Vertices[1], Vertices[6], Vertices[1], Vertices[10], Vertices[4], Vertices[8], Vertices[1], Vertices[2], Vertices[1], Vertices[11], Vertices[8], Vertices[11], Vertices[1]},
            new Vector3[] {Vertices[9], Vertices[6], Vertices[4], Vertices[9], Vertices[3], Vertices[6], Vertices[9], Vertices[1], Vertices[3], Vertices[11], Vertices[6], Vertices[3]},
            new Vector3[] {Vertices[8], Vertices[11], Vertices[1], Vertices[8], Vertices[1], Vertices[0], Vertices[11], Vertices[6], Vertices[1], Vertices[9], Vertices[1], Vertices[4], Vertices[6], Vertices[4], Vertices[1]},
            new Vector3[] {Vertices[3], Vertices[11], Vertices[6], Vertices[3], Vertices[6], Vertices[0], Vertices[0], Vertices[6], Vertices[4]},
            new Vector3[] {Vertices[6], Vertices[4], Vertices[8], Vertices[11], Vertices[6], Vertices[8]},
            new Vector3[] {Vertices[7], Vertices[10], Vertices[6], Vertices[7], Vertices[8], Vertices[10], Vertices[8], Vertices[9], Vertices[10]},
            new Vector3[] {Vertices[0], Vertices[7], Vertices[3], Vertices[0], Vertices[10], Vertices[7], Vertices[0], Vertices[9], Vertices[10], Vertices[6], Vertices[7], Vertices[10]},
            new Vector3[] {Vertices[10], Vertices[6], Vertices[7], Vertices[1], Vertices[10], Vertices[7], Vertices[1], Vertices[7], Vertices[8], Vertices[1], Vertices[8], Vertices[0]},
            new Vector3[] {Vertices[10], Vertices[6], Vertices[7], Vertices[10], Vertices[7], Vertices[1], Vertices[1], Vertices[7], Vertices[3]},
            new Vector3[] {Vertices[1], Vertices[2], Vertices[6], Vertices[1], Vertices[6], Vertices[8], Vertices[1], Vertices[8], Vertices[9], Vertices[8], Vertices[6], Vertices[7]},
            new Vector3[] {Vertices[2], Vertices[6], Vertices[9], Vertices[2], Vertices[9], Vertices[1], Vertices[6], Vertices[7], Vertices[9], Vertices[0], Vertices[9], Vertices[3], Vertices[7], Vertices[3], Vertices[9]},
            new Vector3[] {Vertices[7], Vertices[8], Vertices[0], Vertices[7], Vertices[0], Vertices[6], Vertices[6], Vertices[0], Vertices[2]},
            new Vector3[] {Vertices[7], Vertices[3], Vertices[2], Vertices[6], Vertices[7], Vertices[2]},
            new Vector3[] {Vertices[2], Vertices[3], Vertices[11], Vertices[10], Vertices[6], Vertices[8], Vertices[10], Vertices[8], Vertices[9], Vertices[8], Vertices[6], Vertices[7]},
            new Vector3[] {Vertices[2], Vertices[0], Vertices[7], Vertices[2], Vertices[7], Vertices[11], Vertices[0], Vertices[9], Vertices[7], Vertices[6], Vertices[7], Vertices[10], Vertices[9], Vertices[10], Vertices[7]},
            new Vector3[] {Vertices[1], Vertices[8], Vertices[0], Vertices[1], Vertices[7], Vertices[8], Vertices[1], Vertices[10], Vertices[7], Vertices[6], Vertices[7], Vertices[10], Vertices[2], Vertices[3], Vertices[11]},
            new Vector3[] {Vertices[11], Vertices[2], Vertices[1], Vertices[11], Vertices[1], Vertices[7], Vertices[10], Vertices[6], Vertices[1], Vertices[6], Vertices[7], Vertices[1]},
            new Vector3[] {Vertices[8], Vertices[9], Vertices[6], Vertices[8], Vertices[6], Vertices[7], Vertices[9], Vertices[1], Vertices[6], Vertices[11], Vertices[6], Vertices[3], Vertices[1], Vertices[3], Vertices[6]},
            new Vector3[] {Vertices[0], Vertices[9], Vertices[1], Vertices[11], Vertices[6], Vertices[7]},
            new Vector3[] {Vertices[7], Vertices[8], Vertices[0], Vertices[7], Vertices[0], Vertices[6], Vertices[3], Vertices[11], Vertices[0], Vertices[11], Vertices[6], Vertices[0]},
            new Vector3[] {Vertices[7], Vertices[11], Vertices[6]},
            new Vector3[] {Vertices[7], Vertices[6], Vertices[11]},
            new Vector3[] {Vertices[3], Vertices[0], Vertices[8], Vertices[11], Vertices[7], Vertices[6]},
            new Vector3[] {Vertices[0], Vertices[1], Vertices[9], Vertices[11], Vertices[7], Vertices[6]},
            new Vector3[] {Vertices[8], Vertices[1], Vertices[9], Vertices[8], Vertices[3], Vertices[1], Vertices[11], Vertices[7], Vertices[6]},
            new Vector3[] {Vertices[10], Vertices[1], Vertices[2], Vertices[6], Vertices[11], Vertices[7]},
            new Vector3[] {Vertices[1], Vertices[2], Vertices[10], Vertices[3], Vertices[0], Vertices[8], Vertices[6], Vertices[11], Vertices[7]},
            new Vector3[] {Vertices[2], Vertices[9], Vertices[0], Vertices[2], Vertices[10], Vertices[9], Vertices[6], Vertices[11], Vertices[7]},
            new Vector3[] {Vertices[6], Vertices[11], Vertices[7], Vertices[2], Vertices[10], Vertices[3], Vertices[10], Vertices[8], Vertices[3], Vertices[10], Vertices[9], Vertices[8]},
            new Vector3[] {Vertices[7], Vertices[2], Vertices[3], Vertices[6], Vertices[2], Vertices[7]},
            new Vector3[] {Vertices[7], Vertices[0], Vertices[8], Vertices[7], Vertices[6], Vertices[0], Vertices[6], Vertices[2], Vertices[0]},
            new Vector3[] {Vertices[2], Vertices[7], Vertices[6], Vertices[2], Vertices[3], Vertices[7], Vertices[0], Vertices[1], Vertices[9]},
            new Vector3[] {Vertices[1], Vertices[6], Vertices[2], Vertices[1], Vertices[8], Vertices[6], Vertices[1], Vertices[9], Vertices[8], Vertices[8], Vertices[7], Vertices[6]},
            new Vector3[] {Vertices[10], Vertices[7], Vertices[6], Vertices[10], Vertices[1], Vertices[7], Vertices[1], Vertices[3], Vertices[7]},
            new Vector3[] {Vertices[10], Vertices[7], Vertices[6], Vertices[1], Vertices[7], Vertices[10], Vertices[1], Vertices[8], Vertices[7], Vertices[1], Vertices[0], Vertices[8]},
            new Vector3[] {Vertices[0], Vertices[3], Vertices[7], Vertices[0], Vertices[7], Vertices[10], Vertices[0], Vertices[10], Vertices[9], Vertices[6], Vertices[10], Vertices[7]},
            new Vector3[] {Vertices[7], Vertices[6], Vertices[10], Vertices[7], Vertices[10], Vertices[8], Vertices[8], Vertices[10], Vertices[9]},
            new Vector3[] {Vertices[6], Vertices[8], Vertices[4], Vertices[11], Vertices[8], Vertices[6]},
            new Vector3[] {Vertices[3], Vertices[6], Vertices[11], Vertices[3], Vertices[0], Vertices[6], Vertices[0], Vertices[4], Vertices[6]},
            new Vector3[] {Vertices[8], Vertices[6], Vertices[11], Vertices[8], Vertices[4], Vertices[6], Vertices[9], Vertices[0], Vertices[1]},
            new Vector3[] {Vertices[9], Vertices[4], Vertices[6], Vertices[9], Vertices[6], Vertices[3], Vertices[9], Vertices[3], Vertices[1], Vertices[11], Vertices[3], Vertices[6]},
            new Vector3[] {Vertices[6], Vertices[8], Vertices[4], Vertices[6], Vertices[11], Vertices[8], Vertices[2], Vertices[10], Vertices[1]},
            new Vector3[] {Vertices[1], Vertices[2], Vertices[10], Vertices[3], Vertices[0], Vertices[11], Vertices[0], Vertices[6], Vertices[11], Vertices[0], Vertices[4], Vertices[6]},
            new Vector3[] {Vertices[4], Vertices[11], Vertices[8], Vertices[4], Vertices[6], Vertices[11], Vertices[0], Vertices[2], Vertices[9], Vertices[2], Vertices[10], Vertices[9]},
            new Vector3[] {Vertices[10], Vertices[9], Vertices[3], Vertices[10], Vertices[3], Vertices[2], Vertices[9], Vertices[4], Vertices[3], Vertices[11], Vertices[3], Vertices[6], Vertices[4], Vertices[6], Vertices[3]},
            new Vector3[] {Vertices[8], Vertices[2], Vertices[3], Vertices[8], Vertices[4], Vertices[2], Vertices[4], Vertices[6], Vertices[2]},
            new Vector3[] {Vertices[0], Vertices[4], Vertices[2], Vertices[4], Vertices[6], Vertices[2]},
            new Vector3[] {Vertices[1], Vertices[9], Vertices[0], Vertices[2], Vertices[3], Vertices[4], Vertices[2], Vertices[4], Vertices[6], Vertices[4], Vertices[3], Vertices[8]},
            new Vector3[] {Vertices[1], Vertices[9], Vertices[4], Vertices[1], Vertices[4], Vertices[2], Vertices[2], Vertices[4], Vertices[6]},
            new Vector3[] {Vertices[8], Vertices[1], Vertices[3], Vertices[8], Vertices[6], Vertices[1], Vertices[8], Vertices[4], Vertices[6], Vertices[6], Vertices[10], Vertices[1]},
            new Vector3[] {Vertices[10], Vertices[1], Vertices[0], Vertices[10], Vertices[0], Vertices[6], Vertices[6], Vertices[0], Vertices[4]},
            new Vector3[] {Vertices[4], Vertices[6], Vertices[3], Vertices[4], Vertices[3], Vertices[8], Vertices[6], Vertices[10], Vertices[3], Vertices[0], Vertices[3], Vertices[9], Vertices[10], Vertices[9], Vertices[3]},
            new Vector3[] {Vertices[10], Vertices[9], Vertices[4], Vertices[6], Vertices[10], Vertices[4]},
            new Vector3[] {Vertices[4], Vertices[9], Vertices[5], Vertices[7], Vertices[6], Vertices[11]},
            new Vector3[] {Vertices[0], Vertices[8], Vertices[3], Vertices[4], Vertices[9], Vertices[5], Vertices[11], Vertices[7], Vertices[6]},
            new Vector3[] {Vertices[5], Vertices[0], Vertices[1], Vertices[5], Vertices[4], Vertices[0], Vertices[7], Vertices[6], Vertices[11]},
            new Vector3[] {Vertices[11], Vertices[7], Vertices[6], Vertices[8], Vertices[3], Vertices[4], Vertices[3], Vertices[5], Vertices[4], Vertices[3], Vertices[1], Vertices[5]},
            new Vector3[] {Vertices[9], Vertices[5], Vertices[4], Vertices[10], Vertices[1], Vertices[2], Vertices[7], Vertices[6], Vertices[11]},
            new Vector3[] {Vertices[6], Vertices[11], Vertices[7], Vertices[1], Vertices[2], Vertices[10], Vertices[0], Vertices[8], Vertices[3], Vertices[4], Vertices[9], Vertices[5]},
            new Vector3[] {Vertices[7], Vertices[6], Vertices[11], Vertices[5], Vertices[4], Vertices[10], Vertices[4], Vertices[2], Vertices[10], Vertices[4], Vertices[0], Vertices[2]},
            new Vector3[] {Vertices[3], Vertices[4], Vertices[8], Vertices[3], Vertices[5], Vertices[4], Vertices[3], Vertices[2], Vertices[5], Vertices[10], Vertices[5], Vertices[2], Vertices[11], Vertices[7], Vertices[6]},
            new Vector3[] {Vertices[7], Vertices[2], Vertices[3], Vertices[7], Vertices[6], Vertices[2], Vertices[5], Vertices[4], Vertices[9]},
            new Vector3[] {Vertices[9], Vertices[5], Vertices[4], Vertices[0], Vertices[8], Vertices[6], Vertices[0], Vertices[6], Vertices[2], Vertices[6], Vertices[8], Vertices[7]},
            new Vector3[] {Vertices[3], Vertices[6], Vertices[2], Vertices[3], Vertices[7], Vertices[6], Vertices[1], Vertices[5], Vertices[0], Vertices[5], Vertices[4], Vertices[0]},
            new Vector3[] {Vertices[6], Vertices[2], Vertices[8], Vertices[6], Vertices[8], Vertices[7], Vertices[2], Vertices[1], Vertices[8], Vertices[4], Vertices[8], Vertices[5], Vertices[1], Vertices[5], Vertices[8]},
            new Vector3[] {Vertices[9], Vertices[5], Vertices[4], Vertices[10], Vertices[1], Vertices[6], Vertices[1], Vertices[7], Vertices[6], Vertices[1], Vertices[3], Vertices[7]},
            new Vector3[] {Vertices[1], Vertices[6], Vertices[10], Vertices[1], Vertices[7], Vertices[6], Vertices[1], Vertices[0], Vertices[7], Vertices[8], Vertices[7], Vertices[0], Vertices[9], Vertices[5], Vertices[4]},
            new Vector3[] {Vertices[4], Vertices[0], Vertices[10], Vertices[4], Vertices[10], Vertices[5], Vertices[0], Vertices[3], Vertices[10], Vertices[6], Vertices[10], Vertices[7], Vertices[3], Vertices[7], Vertices[10]},
            new Vector3[] {Vertices[7], Vertices[6], Vertices[10], Vertices[7], Vertices[10], Vertices[8], Vertices[5], Vertices[4], Vertices[10], Vertices[4], Vertices[8], Vertices[10]},
            new Vector3[] {Vertices[6], Vertices[9], Vertices[5], Vertices[6], Vertices[11], Vertices[9], Vertices[11], Vertices[8], Vertices[9]},
            new Vector3[] {Vertices[3], Vertices[6], Vertices[11], Vertices[0], Vertices[6], Vertices[3], Vertices[0], Vertices[5], Vertices[6], Vertices[0], Vertices[9], Vertices[5]},
            new Vector3[] {Vertices[0], Vertices[11], Vertices[8], Vertices[0], Vertices[5], Vertices[11], Vertices[0], Vertices[1], Vertices[5], Vertices[5], Vertices[6], Vertices[11]},
            new Vector3[] {Vertices[6], Vertices[11], Vertices[3], Vertices[6], Vertices[3], Vertices[5], Vertices[5], Vertices[3], Vertices[1]},
            new Vector3[] {Vertices[1], Vertices[2], Vertices[10], Vertices[9], Vertices[5], Vertices[11], Vertices[9], Vertices[11], Vertices[8], Vertices[11], Vertices[5], Vertices[6]},
            new Vector3[] {Vertices[0], Vertices[11], Vertices[3], Vertices[0], Vertices[6], Vertices[11], Vertices[0], Vertices[9], Vertices[6], Vertices[5], Vertices[6], Vertices[9], Vertices[1], Vertices[2], Vertices[10]},
            new Vector3[] {Vertices[11], Vertices[8], Vertices[5], Vertices[11], Vertices[5], Vertices[6], Vertices[8], Vertices[0], Vertices[5], Vertices[10], Vertices[5], Vertices[2], Vertices[0], Vertices[2], Vertices[5]},
            new Vector3[] {Vertices[6], Vertices[11], Vertices[3], Vertices[6], Vertices[3], Vertices[5], Vertices[2], Vertices[10], Vertices[3], Vertices[10], Vertices[5], Vertices[3]},
            new Vector3[] {Vertices[5], Vertices[8], Vertices[9], Vertices[5], Vertices[2], Vertices[8], Vertices[5], Vertices[6], Vertices[2], Vertices[3], Vertices[8], Vertices[2]},
            new Vector3[] {Vertices[9], Vertices[5], Vertices[6], Vertices[9], Vertices[6], Vertices[0], Vertices[0], Vertices[6], Vertices[2]},
            new Vector3[] {Vertices[1], Vertices[5], Vertices[8], Vertices[1], Vertices[8], Vertices[0], Vertices[5], Vertices[6], Vertices[8], Vertices[3], Vertices[8], Vertices[2], Vertices[6], Vertices[2], Vertices[8]},
            new Vector3[] {Vertices[1], Vertices[5], Vertices[6], Vertices[2], Vertices[1], Vertices[6]},
            new Vector3[] {Vertices[1], Vertices[3], Vertices[6], Vertices[1], Vertices[6], Vertices[10], Vertices[3], Vertices[8], Vertices[6], Vertices[5], Vertices[6], Vertices[9], Vertices[8], Vertices[9], Vertices[6]},
            new Vector3[] {Vertices[10], Vertices[1], Vertices[0], Vertices[10], Vertices[0], Vertices[6], Vertices[9], Vertices[5], Vertices[0], Vertices[5], Vertices[6], Vertices[0]},
            new Vector3[] {Vertices[0], Vertices[3], Vertices[8], Vertices[5], Vertices[6], Vertices[10]},
            new Vector3[] {Vertices[10], Vertices[5], Vertices[6]},
            new Vector3[] {Vertices[11], Vertices[5], Vertices[10], Vertices[7], Vertices[5], Vertices[11]},
            new Vector3[] {Vertices[11], Vertices[5], Vertices[10], Vertices[11], Vertices[7], Vertices[5], Vertices[8], Vertices[3], Vertices[0]},
            new Vector3[] {Vertices[5], Vertices[11], Vertices[7], Vertices[5], Vertices[10], Vertices[11], Vertices[1], Vertices[9], Vertices[0]},
            new Vector3[] {Vertices[10], Vertices[7], Vertices[5], Vertices[10], Vertices[11], Vertices[7], Vertices[9], Vertices[8], Vertices[1], Vertices[8], Vertices[3], Vertices[1]},
            new Vector3[] {Vertices[11], Vertices[1], Vertices[2], Vertices[11], Vertices[7], Vertices[1], Vertices[7], Vertices[5], Vertices[1]},
            new Vector3[] {Vertices[0], Vertices[8], Vertices[3], Vertices[1], Vertices[2], Vertices[7], Vertices[1], Vertices[7], Vertices[5], Vertices[7], Vertices[2], Vertices[11]},
            new Vector3[] {Vertices[9], Vertices[7], Vertices[5], Vertices[9], Vertices[2], Vertices[7], Vertices[9], Vertices[0], Vertices[2], Vertices[2], Vertices[11], Vertices[7]},
            new Vector3[] {Vertices[7], Vertices[5], Vertices[2], Vertices[7], Vertices[2], Vertices[11], Vertices[5], Vertices[9], Vertices[2], Vertices[3], Vertices[2], Vertices[8], Vertices[9], Vertices[8], Vertices[2]},
            new Vector3[] {Vertices[2], Vertices[5], Vertices[10], Vertices[2], Vertices[3], Vertices[5], Vertices[3], Vertices[7], Vertices[5]},
            new Vector3[] {Vertices[8], Vertices[2], Vertices[0], Vertices[8], Vertices[5], Vertices[2], Vertices[8], Vertices[7], Vertices[5], Vertices[10], Vertices[2], Vertices[5]},
            new Vector3[] {Vertices[9], Vertices[0], Vertices[1], Vertices[5], Vertices[10], Vertices[3], Vertices[5], Vertices[3], Vertices[7], Vertices[3], Vertices[10], Vertices[2]},
            new Vector3[] {Vertices[9], Vertices[8], Vertices[2], Vertices[9], Vertices[2], Vertices[1], Vertices[8], Vertices[7], Vertices[2], Vertices[10], Vertices[2], Vertices[5], Vertices[7], Vertices[5], Vertices[2]},
            new Vector3[] {Vertices[1], Vertices[3], Vertices[5], Vertices[3], Vertices[7], Vertices[5]},
            new Vector3[] {Vertices[0], Vertices[8], Vertices[7], Vertices[0], Vertices[7], Vertices[1], Vertices[1], Vertices[7], Vertices[5]},
            new Vector3[] {Vertices[9], Vertices[0], Vertices[3], Vertices[9], Vertices[3], Vertices[5], Vertices[5], Vertices[3], Vertices[7]},
            new Vector3[] {Vertices[9], Vertices[8], Vertices[7], Vertices[5], Vertices[9], Vertices[7]},
            new Vector3[] {Vertices[5], Vertices[8], Vertices[4], Vertices[5], Vertices[10], Vertices[8], Vertices[10], Vertices[11], Vertices[8]},
            new Vector3[] {Vertices[5], Vertices[0], Vertices[4], Vertices[5], Vertices[11], Vertices[0], Vertices[5], Vertices[10], Vertices[11], Vertices[11], Vertices[3], Vertices[0]},
            new Vector3[] {Vertices[0], Vertices[1], Vertices[9], Vertices[8], Vertices[4], Vertices[10], Vertices[8], Vertices[10], Vertices[11], Vertices[10], Vertices[4], Vertices[5]},
            new Vector3[] {Vertices[10], Vertices[11], Vertices[4], Vertices[10], Vertices[4], Vertices[5], Vertices[11], Vertices[3], Vertices[4], Vertices[9], Vertices[4], Vertices[1], Vertices[3], Vertices[1], Vertices[4]},
            new Vector3[] {Vertices[2], Vertices[5], Vertices[1], Vertices[2], Vertices[8], Vertices[5], Vertices[2], Vertices[11], Vertices[8], Vertices[4], Vertices[5], Vertices[8]},
            new Vector3[] {Vertices[0], Vertices[4], Vertices[11], Vertices[0], Vertices[11], Vertices[3], Vertices[4], Vertices[5], Vertices[11], Vertices[2], Vertices[11], Vertices[1], Vertices[5], Vertices[1], Vertices[11]},
            new Vector3[] {Vertices[0], Vertices[2], Vertices[5], Vertices[0], Vertices[5], Vertices[9], Vertices[2], Vertices[11], Vertices[5], Vertices[4], Vertices[5], Vertices[8], Vertices[11], Vertices[8], Vertices[5]},
            new Vector3[] {Vertices[9], Vertices[4], Vertices[5], Vertices[2], Vertices[11], Vertices[3]},
            new Vector3[] {Vertices[2], Vertices[5], Vertices[10], Vertices[3], Vertices[5], Vertices[2], Vertices[3], Vertices[4], Vertices[5], Vertices[3], Vertices[8], Vertices[4]},
            new Vector3[] {Vertices[5], Vertices[10], Vertices[2], Vertices[5], Vertices[2], Vertices[4], Vertices[4], Vertices[2], Vertices[0]},
            new Vector3[] {Vertices[3], Vertices[10], Vertices[2], Vertices[3], Vertices[5], Vertices[10], Vertices[3], Vertices[8], Vertices[5], Vertices[4], Vertices[5], Vertices[8], Vertices[0], Vertices[1], Vertices[9]},
            new Vector3[] {Vertices[5], Vertices[10], Vertices[2], Vertices[5], Vertices[2], Vertices[4], Vertices[1], Vertices[9], Vertices[2], Vertices[9], Vertices[4], Vertices[2]},
            new Vector3[] {Vertices[8], Vertices[4], Vertices[5], Vertices[8], Vertices[5], Vertices[3], Vertices[3], Vertices[5], Vertices[1]},
            new Vector3[] {Vertices[0], Vertices[4], Vertices[5], Vertices[1], Vertices[0], Vertices[5]},
            new Vector3[] {Vertices[8], Vertices[4], Vertices[5], Vertices[8], Vertices[5], Vertices[3], Vertices[9], Vertices[0], Vertices[5], Vertices[0], Vertices[3], Vertices[5]},
            new Vector3[] {Vertices[9], Vertices[4], Vertices[5]},
            new Vector3[] {Vertices[4], Vertices[11], Vertices[7], Vertices[4], Vertices[9], Vertices[11], Vertices[9], Vertices[10], Vertices[11]},
            new Vector3[] {Vertices[0], Vertices[8], Vertices[3], Vertices[4], Vertices[9], Vertices[7], Vertices[9], Vertices[11], Vertices[7], Vertices[9], Vertices[10], Vertices[11]},
            new Vector3[] {Vertices[1], Vertices[10], Vertices[11], Vertices[1], Vertices[11], Vertices[4], Vertices[1], Vertices[4], Vertices[0], Vertices[7], Vertices[4], Vertices[11]},
            new Vector3[] {Vertices[3], Vertices[1], Vertices[4], Vertices[3], Vertices[4], Vertices[8], Vertices[1], Vertices[10], Vertices[4], Vertices[7], Vertices[4], Vertices[11], Vertices[10], Vertices[11], Vertices[4]},
            new Vector3[] {Vertices[4], Vertices[11], Vertices[7], Vertices[9], Vertices[11], Vertices[4], Vertices[9], Vertices[2], Vertices[11], Vertices[9], Vertices[1], Vertices[2]},
            new Vector3[] {Vertices[9], Vertices[7], Vertices[4], Vertices[9], Vertices[11], Vertices[7], Vertices[9], Vertices[1], Vertices[11], Vertices[2], Vertices[11], Vertices[1], Vertices[0], Vertices[8], Vertices[3]},
            new Vector3[] {Vertices[11], Vertices[7], Vertices[4], Vertices[11], Vertices[4], Vertices[2], Vertices[2], Vertices[4], Vertices[0]},
            new Vector3[] {Vertices[11], Vertices[7], Vertices[4], Vertices[11], Vertices[4], Vertices[2], Vertices[8], Vertices[3], Vertices[4], Vertices[3], Vertices[2], Vertices[4]},
            new Vector3[] {Vertices[2], Vertices[9], Vertices[10], Vertices[2], Vertices[7], Vertices[9], Vertices[2], Vertices[3], Vertices[7], Vertices[7], Vertices[4], Vertices[9]},
            new Vector3[] {Vertices[9], Vertices[10], Vertices[7], Vertices[9], Vertices[7], Vertices[4], Vertices[10], Vertices[2], Vertices[7], Vertices[8], Vertices[7], Vertices[0], Vertices[2], Vertices[0], Vertices[7]},
            new Vector3[] {Vertices[3], Vertices[7], Vertices[10], Vertices[3], Vertices[10], Vertices[2], Vertices[7], Vertices[4], Vertices[10], Vertices[1], Vertices[10], Vertices[0], Vertices[4], Vertices[0], Vertices[10]},
            new Vector3[] {Vertices[1], Vertices[10], Vertices[2], Vertices[8], Vertices[7], Vertices[4]},
            new Vector3[] {Vertices[4], Vertices[9], Vertices[1], Vertices[4], Vertices[1], Vertices[7], Vertices[7], Vertices[1], Vertices[3]},
            new Vector3[] {Vertices[4], Vertices[9], Vertices[1], Vertices[4], Vertices[1], Vertices[7], Vertices[0], Vertices[8], Vertices[1], Vertices[8], Vertices[7], Vertices[1]},
            new Vector3[] {Vertices[4], Vertices[0], Vertices[3], Vertices[7], Vertices[4], Vertices[3]},
            new Vector3[] {Vertices[4], Vertices[8], Vertices[7]},
            new Vector3[] {Vertices[9], Vertices[10], Vertices[8], Vertices[10], Vertices[11], Vertices[8]},
            new Vector3[] {Vertices[3], Vertices[0], Vertices[9], Vertices[3], Vertices[9], Vertices[11], Vertices[11], Vertices[9], Vertices[10]},
            new Vector3[] {Vertices[0], Vertices[1], Vertices[10], Vertices[0], Vertices[10], Vertices[8], Vertices[8], Vertices[10], Vertices[11]},
            new Vector3[] {Vertices[3], Vertices[1], Vertices[10], Vertices[11], Vertices[3], Vertices[10]},
            new Vector3[] {Vertices[1], Vertices[2], Vertices[11], Vertices[1], Vertices[11], Vertices[9], Vertices[9], Vertices[11], Vertices[8]},
            new Vector3[] {Vertices[3], Vertices[0], Vertices[9], Vertices[3], Vertices[9], Vertices[11], Vertices[1], Vertices[2], Vertices[9], Vertices[2], Vertices[11], Vertices[9]},
            new Vector3[] {Vertices[0], Vertices[2], Vertices[11], Vertices[8], Vertices[0], Vertices[11]},
            new Vector3[] {Vertices[3], Vertices[2], Vertices[11]},
            new Vector3[] {Vertices[2], Vertices[3], Vertices[8], Vertices[2], Vertices[8], Vertices[10], Vertices[10], Vertices[8], Vertices[9]},
            new Vector3[] {Vertices[9], Vertices[10], Vertices[2], Vertices[0], Vertices[9], Vertices[2]},
            new Vector3[] {Vertices[2], Vertices[3], Vertices[8], Vertices[2], Vertices[8], Vertices[10], Vertices[0], Vertices[1], Vertices[8], Vertices[1], Vertices[10], Vertices[8]},
            new Vector3[] {Vertices[1], Vertices[10], Vertices[2]},
            new Vector3[] {Vertices[1], Vertices[3], Vertices[8], Vertices[9], Vertices[1], Vertices[8]},
            new Vector3[] {Vertices[0], Vertices[9], Vertices[1]},
            new Vector3[] {Vertices[0], Vertices[3], Vertices[8]},
            new Vector3[] {}
        };

        private static readonly Vector3[][] NormalTable = new Vector3[][]
        {
            new Vector3[]{},
            new Vector3[]{Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[2],Normals[2],Normals[2],Normals[2],Normals[2],Normals[2]},
            new Vector3[]{Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[4],Normals[4],Normals[4],Normals[4],Normals[4],Normals[4]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[7],Normals[7],Normals[7],Normals[7],Normals[7],Normals[7]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[8],Normals[8],Normals[8],Normals[8],Normals[8],Normals[8]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[5],Normals[5],Normals[5],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[10],Normals[10],Normals[10],Normals[10],Normals[10],Normals[10]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[10],Normals[10],Normals[10],Normals[10],Normals[10],Normals[10],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[4],Normals[4],Normals[4],Normals[4],Normals[4],Normals[4],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[4],Normals[4],Normals[4],Normals[0],Normals[0],Normals[0],Normals[12],Normals[12],Normals[12],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[13],Normals[13],Normals[13]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[9],Normals[9],Normals[9],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[8],Normals[8],Normals[8],Normals[8],Normals[8],Normals[8],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[8],Normals[8],Normals[8],Normals[0],Normals[0],Normals[0],Normals[14],Normals[14],Normals[14],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[3],Normals[3],Normals[3],Normals[5],Normals[5],Normals[5],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[12],Normals[12],Normals[12],Normals[12],Normals[12],Normals[12]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[3],Normals[3],Normals[3],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[7],Normals[7],Normals[7],Normals[7],Normals[7],Normals[7],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[12],Normals[12],Normals[12],Normals[12],Normals[12],Normals[12],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[10],Normals[10],Normals[10],Normals[1],Normals[1],Normals[1],Normals[7],Normals[7],Normals[7],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[8],Normals[8],Normals[8],Normals[8],Normals[8],Normals[8],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[12],Normals[12],Normals[12],Normals[3],Normals[3],Normals[3],Normals[2],Normals[2],Normals[2],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[17],Normals[17],Normals[17],Normals[17],Normals[17],Normals[17]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[11],Normals[11],Normals[11],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[17],Normals[17],Normals[17],Normals[17],Normals[17],Normals[17],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[18],Normals[18],Normals[18],Normals[1],Normals[1],Normals[1],Normals[17],Normals[17],Normals[17],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[17],Normals[17],Normals[17],Normals[17],Normals[17],Normals[17],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[17],Normals[17],Normals[17],Normals[0],Normals[0],Normals[0],Normals[19],Normals[19],Normals[19],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[17],Normals[17],Normals[17],Normals[17],Normals[17],Normals[17],Normals[8],Normals[8],Normals[8],Normals[8],Normals[8],Normals[8]},
            new Vector3[]{Normals[20],Normals[20],Normals[20],Normals[9],Normals[9],Normals[9],Normals[21],Normals[21],Normals[21],Normals[6],Normals[6],Normals[6],Normals[22],Normals[22],Normals[22]},
            new Vector3[]{Normals[22],Normals[22],Normals[22],Normals[3],Normals[3],Normals[3],Normals[23],Normals[23],Normals[23],Normals[15],Normals[15],Normals[15],Normals[20],Normals[20],Normals[20]},
            new Vector3[]{Normals[2],Normals[2],Normals[2],Normals[2],Normals[2],Normals[2]},
            new Vector3[]{Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[2],Normals[2],Normals[2],Normals[2],Normals[2],Normals[2],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[25],Normals[25],Normals[25],Normals[25],Normals[25],Normals[25]},
            new Vector3[]{Normals[25],Normals[25],Normals[25],Normals[25],Normals[25],Normals[25],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[8],Normals[8],Normals[8],Normals[1],Normals[1],Normals[1],Normals[25],Normals[25],Normals[25],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[7],Normals[7],Normals[7],Normals[7],Normals[7],Normals[7],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[6],Normals[6],Normals[6],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[26],Normals[26],Normals[26]},
            new Vector3[]{Normals[7],Normals[7],Normals[7],Normals[3],Normals[3],Normals[3],Normals[14],Normals[14],Normals[14],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[10],Normals[10],Normals[10],Normals[10],Normals[10],Normals[10],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[24],Normals[24],Normals[24],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[0],Normals[0],Normals[0],Normals[11],Normals[11],Normals[11],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[25],Normals[25],Normals[25],Normals[25],Normals[25],Normals[25],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[25],Normals[25],Normals[25],Normals[25],Normals[25],Normals[25],Normals[10],Normals[10],Normals[10],Normals[10],Normals[10],Normals[10]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[27],Normals[27],Normals[27],Normals[0],Normals[0],Normals[0],Normals[28],Normals[28],Normals[28],Normals[3],Normals[3],Normals[3],Normals[29],Normals[29],Normals[29]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[9],Normals[9],Normals[9],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[0],Normals[0],Normals[0],Normals[13],Normals[13],Normals[13],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[9],Normals[9],Normals[9],Normals[6],Normals[6],Normals[6],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[3],Normals[3],Normals[3],Normals[26],Normals[26],Normals[26],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[30],Normals[30],Normals[30],Normals[3],Normals[3],Normals[3],Normals[31],Normals[31],Normals[31],Normals[0],Normals[0],Normals[0],Normals[32],Normals[32],Normals[32]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[18],Normals[18],Normals[18],Normals[18],Normals[18],Normals[18]},
            new Vector3[]{Normals[18],Normals[18],Normals[18],Normals[18],Normals[18],Normals[18],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[2],Normals[2],Normals[2],Normals[15],Normals[15],Normals[15],Normals[4],Normals[4],Normals[4],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[16],Normals[16],Normals[16],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[18],Normals[18],Normals[18],Normals[18],Normals[18],Normals[18],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[7],Normals[7],Normals[7],Normals[7],Normals[7],Normals[7],Normals[18],Normals[18],Normals[18],Normals[18],Normals[18],Normals[18]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[15],Normals[15],Normals[15],Normals[16],Normals[16],Normals[16],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[33],Normals[33],Normals[33],Normals[15],Normals[15],Normals[15],Normals[34],Normals[34],Normals[34],Normals[0],Normals[0],Normals[0],Normals[35],Normals[35],Normals[35]},
            new Vector3[]{Normals[18],Normals[18],Normals[18],Normals[3],Normals[3],Normals[3],Normals[36],Normals[36],Normals[36],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[35],Normals[35],Normals[35],Normals[6],Normals[6],Normals[6],Normals[37],Normals[37],Normals[37],Normals[24],Normals[24],Normals[24],Normals[33],Normals[33],Normals[33]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[4],Normals[4],Normals[4],Normals[4],Normals[4],Normals[4]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[38],Normals[38],Normals[38]},
            new Vector3[]{Normals[10],Normals[10],Normals[10],Normals[15],Normals[15],Normals[15],Normals[19],Normals[19],Normals[19],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[25],Normals[25],Normals[25],Normals[15],Normals[15],Normals[15],Normals[36],Normals[36],Normals[36],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[29],Normals[29],Normals[29],Normals[24],Normals[24],Normals[24],Normals[39],Normals[39],Normals[39],Normals[9],Normals[9],Normals[9],Normals[27],Normals[27],Normals[27]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[12],Normals[12],Normals[12],Normals[12],Normals[12],Normals[12]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[15],Normals[15],Normals[15],Normals[38],Normals[38],Normals[38],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[40],Normals[40],Normals[40],Normals[0],Normals[0],Normals[0],Normals[41],Normals[41],Normals[41],Normals[15],Normals[15],Normals[15],Normals[42],Normals[42],Normals[42]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[43],Normals[43],Normals[43],Normals[15],Normals[15],Normals[15],Normals[44],Normals[44],Normals[44],Normals[3],Normals[3],Normals[3],Normals[45],Normals[45],Normals[45]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[2],Normals[2],Normals[2],Normals[2],Normals[2],Normals[2],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[0],Normals[0],Normals[0],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[4],Normals[4],Normals[4],Normals[4],Normals[4],Normals[4],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[14],Normals[14],Normals[14],Normals[14],Normals[14],Normals[14]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[13],Normals[13],Normals[13]},
            new Vector3[]{Normals[14],Normals[14],Normals[14],Normals[14],Normals[14],Normals[14],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[10],Normals[10],Normals[10],Normals[6],Normals[6],Normals[6],Normals[2],Normals[2],Normals[2],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[26],Normals[26],Normals[26]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[25],Normals[25],Normals[25],Normals[6],Normals[6],Normals[6],Normals[4],Normals[4],Normals[4],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[5],Normals[5],Normals[5]},
            new Vector3[]{Normals[19],Normals[19],Normals[19],Normals[19],Normals[19],Normals[19]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[13],Normals[13],Normals[13]},
            new Vector3[]{Normals[19],Normals[19],Normals[19],Normals[19],Normals[19],Normals[19],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[7],Normals[7],Normals[7],Normals[9],Normals[9],Normals[9],Normals[2],Normals[2],Normals[2],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[19],Normals[19],Normals[19],Normals[19],Normals[19],Normals[19],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[13],Normals[13],Normals[13]},
            new Vector3[]{Normals[19],Normals[19],Normals[19],Normals[19],Normals[19],Normals[19],Normals[4],Normals[4],Normals[4],Normals[4],Normals[4],Normals[4]},
            new Vector3[]{Normals[47],Normals[47],Normals[47],Normals[1],Normals[1],Normals[1],Normals[48],Normals[48],Normals[48],Normals[9],Normals[9],Normals[9],Normals[49],Normals[49],Normals[49]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[13],Normals[13],Normals[13]},
            new Vector3[]{Normals[13],Normals[13],Normals[13],Normals[13],Normals[13],Normals[13]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[46],Normals[46],Normals[46],Normals[13],Normals[13],Normals[13],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[13],Normals[13],Normals[13]},
            new Vector3[]{Normals[36],Normals[36],Normals[36],Normals[6],Normals[6],Normals[6],Normals[19],Normals[19],Normals[19],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[13],Normals[13],Normals[13]},
            new Vector3[]{Normals[49],Normals[49],Normals[49],Normals[46],Normals[46],Normals[46],Normals[50],Normals[50],Normals[50],Normals[3],Normals[3],Normals[3],Normals[47],Normals[47],Normals[47]},
            new Vector3[]{Normals[7],Normals[7],Normals[7],Normals[7],Normals[7],Normals[7]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[15],Normals[15],Normals[15],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[12],Normals[12],Normals[12],Normals[12],Normals[12],Normals[12],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[3],Normals[3],Normals[3],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[3],Normals[3],Normals[3],Normals[0],Normals[0],Normals[0],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[14],Normals[14],Normals[14],Normals[14],Normals[14],Normals[14],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[6],Normals[6],Normals[6],Normals[13],Normals[13],Normals[13],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[14],Normals[14],Normals[14],Normals[14],Normals[14],Normals[14],Normals[12],Normals[12],Normals[12],Normals[12],Normals[12],Normals[12]},
            new Vector3[]{Normals[51],Normals[51],Normals[51],Normals[6],Normals[6],Normals[6],Normals[52],Normals[52],Normals[52],Normals[1],Normals[1],Normals[1],Normals[53],Normals[53],Normals[53]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[26],Normals[26],Normals[26]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[54],Normals[54],Normals[54],Normals[1],Normals[1],Normals[1],Normals[55],Normals[55],Normals[55],Normals[6],Normals[6],Normals[6],Normals[56],Normals[56],Normals[56]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[38],Normals[38],Normals[38]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[18],Normals[18],Normals[18],Normals[9],Normals[9],Normals[9],Normals[12],Normals[12],Normals[12],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[11],Normals[11],Normals[11]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[9],Normals[9],Normals[9],Normals[38],Normals[38],Normals[38],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[57],Normals[57],Normals[57],Normals[9],Normals[9],Normals[9],Normals[58],Normals[58],Normals[58],Normals[1],Normals[1],Normals[1],Normals[59],Normals[59],Normals[59]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[17],Normals[17],Normals[17],Normals[46],Normals[46],Normals[46],Normals[10],Normals[10],Normals[10],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[13],Normals[13],Normals[13]},
            new Vector3[]{Normals[53],Normals[53],Normals[53],Normals[15],Normals[15],Normals[15],Normals[60],Normals[60],Normals[60],Normals[46],Normals[46],Normals[46],Normals[51],Normals[51],Normals[51]},
            new Vector3[]{Normals[10],Normals[10],Normals[10],Normals[10],Normals[10],Normals[10]},
            new Vector3[]{Normals[45],Normals[45],Normals[45],Normals[6],Normals[6],Normals[6],Normals[61],Normals[61],Normals[61],Normals[9],Normals[9],Normals[9],Normals[43],Normals[43],Normals[43]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[36],Normals[36],Normals[36],Normals[36],Normals[36],Normals[36]},
            new Vector3[]{Normals[36],Normals[36],Normals[36],Normals[36],Normals[36],Normals[36],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[36],Normals[36],Normals[36],Normals[36],Normals[36],Normals[36],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[36],Normals[36],Normals[36],Normals[36],Normals[36],Normals[36],Normals[2],Normals[2],Normals[2],Normals[2],Normals[2],Normals[2]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[26],Normals[26],Normals[26]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[24],Normals[24],Normals[24],Normals[26],Normals[26],Normals[26],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[8],Normals[8],Normals[8],Normals[24],Normals[24],Normals[24],Normals[4],Normals[4],Normals[4],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[62],Normals[62],Normals[62],Normals[24],Normals[24],Normals[24],Normals[63],Normals[63],Normals[63],Normals[1],Normals[1],Normals[1],Normals[64],Normals[64],Normals[64]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[26],Normals[26],Normals[26]},
            new Vector3[]{Normals[7],Normals[7],Normals[7],Normals[46],Normals[46],Normals[46],Normals[8],Normals[8],Normals[8],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[46],Normals[46],Normals[46],Normals[26],Normals[26],Normals[26],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[64],Normals[64],Normals[64],Normals[0],Normals[0],Normals[0],Normals[65],Normals[65],Normals[65],Normals[46],Normals[46],Normals[46],Normals[62],Normals[62],Normals[62]},
            new Vector3[]{Normals[26],Normals[26],Normals[26],Normals[26],Normals[26],Normals[26]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[26],Normals[26],Normals[26]},
            new Vector3[]{Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[26],Normals[26],Normals[26]},
            new Vector3[]{Normals[8],Normals[8],Normals[8],Normals[8],Normals[8],Normals[8]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[38],Normals[38],Normals[38]},
            new Vector3[]{Normals[14],Normals[14],Normals[14],Normals[9],Normals[9],Normals[9],Normals[36],Normals[36],Normals[36],Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[1],Normals[1],Normals[1],Normals[46],Normals[46],Normals[46],Normals[38],Normals[38],Normals[38],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[66],Normals[66],Normals[66],Normals[46],Normals[46],Normals[46],Normals[67],Normals[67],Normals[67],Normals[0],Normals[0],Normals[0],Normals[68],Normals[68],Normals[68]},
            new Vector3[]{Normals[25],Normals[25],Normals[25],Normals[46],Normals[46],Normals[46],Normals[18],Normals[18],Normals[18],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[32],Normals[32],Normals[32],Normals[9],Normals[9],Normals[9],Normals[69],Normals[69],Normals[69],Normals[24],Normals[24],Normals[24],Normals[30],Normals[30],Normals[30]},
            new Vector3[]{Normals[59],Normals[59],Normals[59],Normals[3],Normals[3],Normals[3],Normals[70],Normals[70],Normals[70],Normals[46],Normals[46],Normals[46],Normals[57],Normals[57],Normals[57]},
            new Vector3[]{Normals[6],Normals[6],Normals[6],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[13],Normals[13],Normals[13]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[26],Normals[26],Normals[26]},
            new Vector3[]{Normals[14],Normals[14],Normals[14],Normals[14],Normals[14],Normals[14]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[38],Normals[38],Normals[38]},
            new Vector3[]{Normals[0],Normals[0],Normals[0],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[38],Normals[38],Normals[38]},
            new Vector3[]{Normals[17],Normals[17],Normals[17],Normals[24],Normals[24],Normals[24],Normals[12],Normals[12],Normals[12],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[68],Normals[68],Normals[68],Normals[1],Normals[1],Normals[1],Normals[71],Normals[71],Normals[71],Normals[24],Normals[24],Normals[24],Normals[66],Normals[66],Normals[66]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[0],Normals[0],Normals[0]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[16],Normals[16],Normals[16]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1],Normals[1]},
            new Vector3[]{Normals[19],Normals[19],Normals[19],Normals[24],Normals[24],Normals[24],Normals[14],Normals[14],Normals[14],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[42],Normals[42],Normals[42],Normals[24],Normals[24],Normals[24],Normals[72],Normals[72],Normals[72],Normals[6],Normals[6],Normals[6],Normals[40],Normals[40],Normals[40]},
            new Vector3[]{Normals[56],Normals[56],Normals[56],Normals[46],Normals[46],Normals[46],Normals[73],Normals[73],Normals[73],Normals[15],Normals[15],Normals[15],Normals[54],Normals[54],Normals[54]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[26],Normals[26],Normals[26]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6],Normals[6]},
            new Vector3[]{Normals[25],Normals[25],Normals[25],Normals[25],Normals[25],Normals[25]},
            new Vector3[]{Normals[3],Normals[3],Normals[3]},
            new Vector3[]{Normals[38],Normals[38],Normals[38],Normals[38],Normals[38],Normals[38]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[38],Normals[38],Normals[38]},
            new Vector3[]{Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[38],Normals[38],Normals[38]},
            new Vector3[]{Normals[17],Normals[17],Normals[17],Normals[17],Normals[17],Normals[17]},
            new Vector3[]{Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[38],Normals[38],Normals[38]},
            new Vector3[]{Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[9],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24],Normals[24]},
            new Vector3[]{Normals[18],Normals[18],Normals[18],Normals[18],Normals[18],Normals[18]},
            new Vector3[]{Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[38],Normals[38],Normals[38]},
            new Vector3[]{Normals[19],Normals[19],Normals[19],Normals[19],Normals[19],Normals[19]},
            new Vector3[]{Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[46],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15],Normals[15]},
            new Vector3[]{Normals[9],Normals[9],Normals[9]},
            new Vector3[]{Normals[36],Normals[36],Normals[36],Normals[36],Normals[36],Normals[36]},
            new Vector3[]{Normals[46],Normals[46],Normals[46]},
            new Vector3[]{Normals[24],Normals[24],Normals[24]},
            new Vector3[]{}
        };


        internal static void SetAllMeshInfo(bool[] scalars, out Vector3[] vertices, out int[] triangles, out Vector3[] normals)
        {
            int key = 0;
            if (!scalars[0]) key |= 1;
            if (!scalars[1]) key |= 2;
            if (!scalars[2]) key |= 4;
            if (!scalars[3]) key |= 8;
            if (!scalars[4]) key |= 16;
            if (!scalars[5]) key |= 32;
            if (!scalars[6]) key |= 64;
            if (!scalars[7]) key |= 128;

            vertices = VerticeTable[key];
            normals = NormalTable[key];
            triangles = TriangleTable[normals.Length];
        }


    }
}